site_name: Makim
site_url: https://osl-incubator.github.io/makim
repo_url: https://github.com/osl-incubator/makim.git
docs_dir: ./docs
site_dir: ./build

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  logo: ./images/logo.png
  favicon: ./images/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - macros
  - mkdocstrings
  - mkdocs-jupyter:
      execute: false
      include: ["*.ipynb"]
      ignore:
        - "*.py"
        - ".ipynb_checkpoints/*"
      include_source: true
      include_requirejs: true
  - literate-nav

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      provider: github
      repo_url_shortener: true
  - pymdownx.saneheaders
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables
  - toc:
      permalink: true

extra:
  project_name: "Makim"
  team:
    - name: "Active maintainers"
      members:
        - xmnlab
    - name: "Former maintainers"
      members:
        - xmnlab
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opensciencelabs
    - icon: fontawesome/brands/github
      link: https://github.com/osl-incubator/makim.git
  support_levels:
    supported:
      icon: :material-check-decagram:{ .verified }
      description: Tested in CI. If this doesn't work for you, please [file an issue](https://github.com/osl-incubator/makim.git/issues/new).
    bug:
      icon: :material-bug:{ .bug }
      description: Should work but doesn't because upstream is broken. Supported on a best-effort basis.
    unsupported:
      icon: :material-cancel:{ .cancel }
      description: Unlikely to ever be supported or no upstream support.

copyright: "Copyright &copy; 2025, Makim Team"
